spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zblog?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
logging:
  level:
    root: info
    com.zt.blog: debug
  file:
    name: log/zblog-dev.log

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
